backend:
  name: git-gateway
  branch: main

# when using the default proxy server port
local_backend: true
# This line should *not* be indented
publish_mode: editorial_workflow

media_folder: static/img # Folder where user uploaded files should go
public_folder: /img

search: true

slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: authors
    identifier_field: name
    label: Authors
    folder: content/authors
    create: true
    slug: "{{slug}}"
    summary: "{{name}}: {{occupation}}"
    fields:
      - { label: Name, name: name, widget: string }
      - {
          label: Avatar,
          name: avatar,
          widget: image,
          choose_url: true,
          allow_multiple: false,
          required: false,
        }
      - { label: Occupation, name: occupation, widget: string, required: false }
      - { label: Company, name: company, widget: string, required: false }
      - { label: Email, name: email, widget: string, required: false }
      - { label: Twitter, name: twitter, widget: string, required: false }
      - { label: LinkedIn, name: linkedin, widget: string, required: false }
      - { label: GitHub, name: github, widget: string, required: false }
      - { label: About, name: "body", widget: "markdown" }


  - name: posts # Used in routes, e.g., /admin/collections/blog
    identifier_field: title
    label: Posts # Used in the UI
    folder: content/posts # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter

      - { label: Title,
          name: title,
          widget: string 
          }

      - { label: Subtitle,
          name: subtitle,
          widget: string,
          required: false }
      - {
          label: "Publish Date",
          name: date,
          widget: date,
          default: "",
          format: "YYYY-MM-DD",
        }

      - {
          label: Draft,
          name: draft,
          widget: boolean,
          default: true,
          required: false,
        }
      - { label: Summary,
          name: summary,
          widget: string,
          required: false }

      - { label: "Tags",
          name: "tags",
          widget: "list",
          allow_multiple: true,
          allow_add: true }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          choose_url: true,
          allow_multiple: false,
          required: false,
        }

      - {
          label: Author,
          name: author,
          widget: relation,
          collection: authors,
          search_fields: ["name"],
          value_field: name,
          display_fields: ["name"],
        }
      - { label: Body, name: "body", widget: "markdown" }

  - name: projects # Used in routes, e.g., /admin/collections/blog
    identifier_field: title
    label: Projects # Used in the UI
    folder: content/projects # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: Title, name: title, widget: string, required: true }
      - {
          label: "Date",
          name: date,
          widget: date,
          default: "",
          format: "YYYY-MM-DD",
        }
      - {
          label: Draft,
          name: draft,
          widget: boolean,
          default: false,
          required: false,
        }
      - { label: "Tag", name: "tags", widget: "list", allow_add: true }
      - {
          label: Description,
          name: description,
          widget: string,
          required: true,
        }
      - {
          label: "Github Link",
          name: "github_link",
          widget: "string",
          required: false,
          allow_multiple: false,
        }
      - {
          label: "Demo Link",
          name: "demo_link",
          widget: "string",
          required: false,
          allow_multiple: false,
        }
      - {
          label: "Blog Link",
          name: "blog_link",
          widget: "string",
          required: false,
          allow_multiple: false,
        }

      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          choose_url: true,
          allow_multiple: false,
          required: false,
        }
      # - { label: Body, name: "body", widget: "markdown", required: false }
